# based on http://www.deveria.com/alexis/lemmings/lemmings/amigacodes.html
# and http://home.wanadoo.nl/lemmings-solution/index2.html
# and http://www.deinonych.com/lemmings/lemm1fun_walk.shtml

name = PSP Lemmings

codeSeed = AJHLDHBBCJ

# music selection
music_0 = psp/crystal1.ogg
music_1 = psp/crystal2.ogg
music_2 = psp/crystal3.ogg
music_3 = psp/earth1.ogg
music_4 = psp/earth2.ogg
music_5 = psp/earth3.ogg
music_6 = psp/egypt1.ogg
music_7 = psp/egypt2.ogg
music_8 = psp/egypt3.ogg
music_9 = psp/hell1.ogg
music_10 = psp/hell2.ogg
music_11 = psp/hell3.ogg
music_12 = psp/oldtune1.ogg
music_13 = psp/oldtune2.ogg
music_14 = psp/oldtune3.ogg
music_15 = psp/roman1.ogg
music_16 = psp/roman2.ogg
music_17 = psp/roman3.ogg


# ratings
level_0 = PSP Extra Levels

# Levels: name, music ID
# Rating 0 - Level

# Level 1 Climb to Victory
level_0_0 = 01 Climb to Victory.rlv,14
# Level 2 Save The Lemmings With Floaters
level_0_1 = 02 Save The Lemmings With Floaters.rlv,6
# Level 3 Dig Down, Bash Across
level_0_2 = 03 Dig Down Bash Across.rlv,10
# Level 4 Block First, Explode Second
level_0_3 = 04 Block First Explode Second.rlv,17
# Level 5 Bridge Across, Mine Through
level_0_4 = 05 Bridge Across Mine Through.rlv,2
# Level 6 Bash in the Direction of the Arrows
level_0_5 = 06 Bash in the Direction of the Arrows.rlv,14
# Level 7 Crystal Point
level_0_6 = 07 Crystal Point.rlv,2
# Level   So Near, So Far
level_0_7 = 08 So Near So Far.rlv,9
# Level 9 Pillar Talking
level_0_8 = 09 Pillar Talking.rlv,8
# Level 10 Just 17
level_0_9 = 10 Just 17.rlv,6
# Level 11 Down The Line
level_0_10 = 11 Down The Line.rlv,16
# Level 12 A to B
level_0_11 = 12 A to B.rlv,13
# Level 13 Chain Reaction
level_0_12 = 13 Chain Reaction.rlv,10
# Level 14 Tunnel Vision
level_0_13 = 14 Tunnel Vision.rlv,8
# Level 15 Two Good Friends
level_0_14 = 15 Two Good Friends.rlv,6
# Level 16 One Man Does All The Hard Work
level_0_15 = 16 One Man Does All The Hard Work.rlv,0
# Level 17 Release is the Word
level_0_16 = 17 Release is the Word.rlv,10
# Level 18 The Run Around
level_0_17 = 18 The Run Around.rlv,12
# Level 19 Three Steps to Heaven
level_0_18 = 19 Three Steps to Heaven.rlv,0
# Level 20 Lemming Toast
level_0_19 = 20 Lemming Toast.rlv,10
# level 21 Seeing Double
level_0_20 = 21 Seeing Double.rlv,15
# level 22 The Wormery
level_0_21 = 22 The Wormery.rlv,3
# level 23 The Flood
level_0_22 = 23 The Flood.rlv,6
# level 24 With a Little Help From My Lem
level_0_23 = 24 With a Little Help From My Lem.rlv,17
# level 25 Not As Easy As It Looks
level_0_24 = 25 Not As Easy As It Looks.rlv,16
# level 26 Back Of The Net!
level_0_25 = 26 Back Of The Net.rlv,0
# level 27 Wrong Point Of View
level_0_26 = 27 Wrong Point Of View.rlv,1
# level 28 Float in Light, at Lemming Head Height
level_0_27 = 28 Float in Light at Lemming Head Height.rlv,7
# level 29 A Bridge Over Lemming Slaughtered
level_0_28 = 29 A Bridge Over Lemming Slaughtered.rlv,16
# level 30 The Stairs Are Not Floored
level_0_29 = 30 The Stairs Are Not Floored.rlv,7
# level 31 Quickly Now!
level_0_30 = 31 Quickly Now.rlv,9
# level 32 Gather Round and Break Away
level_0_31 = 32 Gather Round and Break Away.rlv,10
# level 33 Cagey Business
level_0_32 = 33 Cagey Business.rlv,15
# level 34 Born a Blocker, Die a Blocker
level_0_33 = 34 Born a Blocker Die a Blocker.rlv,15
# level 35 No Justice for the Hero
level_0_34 = 35 No Justice for the Hero.rlv,2
# level 36 Notch What You Think It Is!
level_0_35 = 36 Notch What You Think It Is.rlv,17
  


