# SuperLemmini graphic set
# Created with NeoLemmix Graphic Set Tool
bgColor = 0x000030
debrisColor = 0x00A8FC

# Terrain
tiles = 58
steelTiles = 26,27,28,29,30

# Objects
# Object 0: Exit
frames_0 = 1
speed_0 = 2
anim_0 = 0
type_0 = 8
maskOffsetX_0 = 32
maskOffsetY_0 = 40
sound_0 = 14

# Object 1: Window
frames_1 = 7
speed_1 = 2
anim_1 = 3
type_1 = 32
maskOffsetX_1 = -2
maskOffsetY_1 = 6
sound_1 = 5

# Object 2: Water
frames_2 = 6
speed_2 = 2
anim_2 = 1
type_2 = 5
maskOffsetX_2 = 0
maskOffsetY_2 = 8
sound_2 = 17

# Object 3: No effect
frames_3 = 3
speed_3 = 2
anim_3 = 1
type_3 = 0
maskOffsetX_3 = 0
maskOffsetY_3 = -8
sound_3 = -1

# Object 4: Triggered trap
frames_4 = 15
speed_4 = 2
anim_4 = 2
type_4 = 6
maskOffsetX_4 = 8
maskOffsetY_4 = 80
sound_4 = 11,4

# revision
revision = 2.8