# animation types
# 0 - don't animate
# 1 - animate continuously
# 2 - trap - animate on trigger - else show first pic
# 3 - entrance animation: animate once at level start

# object types
# 0  - passive
# 1  - turn left
# 2  - turn right
# 3  - no digging to the left
# 4  - no digging to the right
# 5  - trap that makes lemmings drown (water/quick sand/mud)
# 6  - trap that removes lemming
# 7  - trap that triggers lemming death animation
# 8  - exit
# 9  - steel
# 32 - entrance

bgColor = 0x000030
debrisColor = 0x00A8FC

# Terrain
steelTiles = 26,27,28,29,30

# Objects
# Object 0: Exit
frames_0 = 1
speed_0 = 2
anim_0 = 0
type_0 = 8
maskOffsetX_0 = 32
maskOffsetY_0 = 40
sound_0 = 14

# Object 1: Window
frames_1 = 7
speed_1 = 2
anim_1 = 3
type_1 = 32
maskOffsetX_1 = -2
maskOffsetY_1 = 6
sound_1 = 5

# Object 2: Water
frames_2 = 6
speed_2 = 2
anim_2 = 1
type_2 = 5
maskOffsetX_2 = 0
maskOffsetY_2 = 8
sound_2 = 17

# Object 3: No effect
frames_3 = 3
speed_3 = 2
anim_3 = 1
type_3 = 0
maskOffsetX_3 = 0
maskOffsetY_3 = -8
sound_3 = -1

# Object 4: Triggered trap
frames_4 = 15
speed_4 = 2
anim_4 = 2
type_4 = 6
maskOffsetX_4 = 8
maskOffsetY_4 = 80
sound_4 = 11,4

# arrows left - always animate
frames_5      = 7
speed_5       = 2
anim_5         = 1
type_5         = 4
maskOffsetX_5 = 0
maskOffsetY_5  = 0
sound_5        = 3

# arrows right - always animate
frames_6       = 7
speed_6        = 2
anim_6         = 1
type_6         = 3
maskOffsetX_6  = 0
maskOffsetY_6  = 0
sound_6        = 3