bgColor   = 0x000030
debrisColor = 0xf0f060
particleColor  = 0xffffff,0x4040e0,0x00b000,0xf0d0d0,0xf0f000,0xf02020,0x808080,0xf0f060,0xf0f060,0xd0b040,0xb08020,0xa05000,0x803010,0x500000,0x606070,0x404050

# classico_0
deprecated_0
frames_0       = 1
speed_0        = 2
anim_0         = 0
type_0         = 0
maskOffsetX_0  = 0
maskOffsetY_0  = 0
sound_0        = -1

# window - animate once
frames_1 = 10
speed_1 = 2
anim_1 = 3
type_1 = 32
maskOffsetX_1 = 0
maskOffsetY_1 = 0
sound_1 = 5

# exit - full image - always animate
frames_2       = 6
speed_2        = 2
anim_2         = 1
type_2         = 8
maskOffsetX_2  = 0
maskOffsetY_2  = 6
sound_2        = 23

# water - always animate
frames_3 = 8
speed_3 = 2
anim_3 = 1
type_3 = 5
maskOffsetX_3 = 0
maskOffsetY_3 = 7
sound_3 = 17

# fire - always animate
frames_4 = 10
speed_4 = 2
anim_4 = 1
type_4 = 7
maskOffsetX_4 = 40
maskOffsetY_4 = -7
sound_4 = 8
