name = Untitled

codeSeed = GKCPQTPNSO


# Music selection
music_0 = zxspectrum/orig_13-tim1ZXSpectrum.ogg

# Groups
level_0 = ZX Spectrum

# Levels: name, music ID

# Rating 0 - ZX Spectrum

level_0_0 = 101 Origins And Lemmings.rlv,0
level_0_1 = 102 Don't Let Your Eyes Deceive You.rlv,1
level_0_2 = 103 Don't Do Anything Too Hasty.rlv,2
level_0_3 = 201 Lemmings Lemmings Everywhere.rlv,3
level_0_4 = 202 Timing Is Critical.rlv,4
level_0_5 = 203 Reflex Actions.rlv,5
level_0_6 = 204 Lemming Sanctuary In Sight.rlv,6
level_0_7 = 301 The Crankshaft.rlv,7
level_0_8 = 302 If At First You Don't Succeed.rlv,8
level_0_9 = 303 A Memory Test.rlv,9
level_0_10 = 304 King Of The Castle.rlv,10
level_0_11 = 305 It's A Race Against Time.rlv,11
level_0_12 = 401 Speed Trap.rlv,12
level_0_13 = 402 Is This A Doddle.rlv,13
level_0_14 = 403 Heaven Can Wait (We Hope!!!!).rlv,14
level_0_15 = 404 Dig For Victory.rlv,15
level_0_16 = 405 Jon's Mayhem Level.rlv,16
level_0_17 = 406 Sleepless Nights.rlv,17
level_0_18 = 407 Pride Comes Before.rlv,18
level_0_19 = 408 Environmentally Friendly.rlv,19

