name = Genesis (MegaDrive) Lemmings

codeSeed = HMCLMGCIKK


# Music selection
music_0 = genesis/orig_01-cancangenesis.ogg
music_1 = genesis/orig_02-lemming1genesis.ogg
music_2 = genesis/orig_03-tim2genesis.ogg
music_3 = genesis/orig_04-lemming2genesis.ogg
music_4 = genesis/orig_05-tim8genesis.ogg
music_5 = genesis/orig_06-tim3genesis.ogg
music_6 = genesis/orig_07-tim5genesis.ogg
music_7 = genesis/orig_08-doggiegenesis.ogg
music_8 = genesis/orig_09-tim6genesis.ogg
music_9 = genesis/orig_10-lemming3genesis.ogg
music_10 = genesis/orig_11-tim7genesis.ogg
music_11 = genesis/orig_12-tim9genesis.ogg
music_12 = genesis/orig_13-tim1genesis.ogg
music_13 = genesis/orig_14-tim10genesis.ogg
music_14 = genesis/orig_15-tim4genesis.ogg
music_15 = genesis/orig_16-tenlemmsgenesis.ogg
music_16 = genesis/orig_17-mountaingenesis.ogg
music_17 = genesis/special/beasti_genesis.ogg
music_18 = genesis/special/menace_genesis.ogg
music_19 = genesis/special/awesome_genesis.ogg
music_20 = genesis/special/beastii_genesis.ogg
music_21 = genesis/special/Sunsoft Special_genesis.ogg

# Groups
level_0 = Fun
level_1 = Tricky
level_2 = Taxing
level_3 = Mayhem
level_4 = Present
level_5 = Sunsoft
level_6 = 2-Player

# Levels: name, music ID

# Rating 0 - Fun

level_0_0 = 101 Just Dig.rlv,0
level_0_1 = 102 Only Floaters Can Survive This.rlv,1
level_0_2 = 103 Tailor-made For Blockers.rlv,2
level_0_3 = 104 Now Use Miners And Climbers.rlv,3
level_0_4 = 105 You Need Bashers This Time.rlv,4
level_0_5 = 106 A Task For Blockers And Bombers.rlv,5
level_0_6 = 107 Builders Will Help You Here.rlv,6
level_0_7 = 108 Not As Complicated As It Looks.rlv,7
level_0_8 = 109 As Long As You Try Your Best.rlv,8
level_0_9 = 110 5 Miles If You Love Lemmings.rlv,9
level_0_10 = 111 Keep Your Hair On Mr Lemming.rlv,10
level_0_11 = 112 Patience.rlv,0
level_0_12 = 113 We All Fall Down.rlv,11
level_0_13 = 114 Room With No Exit.rlv,4
level_0_14 = 115 Tea Time in the Ball Country.rlv,12
level_0_15 = 116 Take A Little Rest.rlv,13
level_0_16 = 117 Easy When You Know How.rlv,14
level_0_17 = 118 Let's Block And Blow.rlv,12
level_0_18 = 119 Catch More Floaters.rlv,6
level_0_19 = 120 We Are Now At LEMCON ONE.rlv,7
level_0_20 = 121 Lemmings in the Attic.rlv,15
level_0_21 = 122 A Beast Of A Level.rlv,17
level_0_22 = 123 Under Construction.rlv,4
level_0_23 = 124 Konbanwa Lemming san.rlv,11
level_0_24 = 125 Lemmings Lemmings Everywhere.rlv,10
level_0_25 = 126 The Great Lemming Caper.rlv,1
level_0_26 = 127 Let's Be Careful Out There.rlv,4
level_0_27 = 128 If Only They Could Fly.rlv,8
level_0_28 = 129 Dark Dawn.rlv,10
level_0_29 = 130 Lock Up Your Lemmings.rlv,4

# Rating 1 - Tricky

level_1_0 = 201 We All Fall Down.rlv,8
level_1_1 = 202 A Ladder Would Be Handy.rlv,9
level_1_2 = 203 Lemmingology.rlv,10
level_1_3 = 204 The Ascending Pillar Scenario.rlv,16
level_1_4 = 205 Lemming Sanctuary in Sight.rlv,7
level_1_5 = 206 Lemmings in the Attic.rlv,5
level_1_6 = 207 Bitter Lemming.rlv,1
level_1_7 = 208 Lemming Drops.rlv,0
level_1_8 = 209 Where Do You See Lemmings.rlv,4
level_1_9 = 210 Keep Step.rlv,7
level_1_10 = 211 Let's Go To The Moon.rlv,6
level_1_11 = 212 Go Out For a Walk.rlv,11
level_1_12 = 213 Salvage Boat.rlv,12
level_1_13 = 214 MENACING.rlv,18
level_1_14 = 215 Ozone Friendly Lemmings.rlv,4
level_1_15 = 216 Lovely Jubilee.rlv,13
level_1_16 = 217 Diet Lemmingaid.rlv,8
level_1_17 = 218 It's Lemmingentry Watson.rlv,14
level_1_18 = 219 Postcard From Lemmingland.rlv,1
level_1_19 = 220 One Way Digging To Freedom.rlv,2
level_1_20 = 221 Don't Leave Any Lemmings.rlv,7
level_1_21 = 222 Turn Around Young Lemmings.rlv,5
level_1_22 = 223 From The Boundary Line.rlv,3
level_1_23 = 224 Tightrope City.rlv,9
level_1_24 = 225 Cascade.rlv,4
level_1_25 = 226 I Have a Cunning Plan.rlv,1
level_1_26 = 227 Everybody Turn Left.rlv,0
level_1_27 = 228 Lost Something.rlv,7
level_1_28 = 229 Konnichiwa Lemming san.rlv,5
level_1_29 = 230 Don't follow me.rlv,6

# Rating 2 - Taxing

level_2_0 = 301 The Bridge is Breaking Down.rlv,4
level_2_1 = 302 Temporary Peace.rlv,5
level_2_2 = 303 No Choice But To Follow Them.rlv,3
level_2_3 = 304 Lend a Helping Hand.rlv,9
level_2_4 = 305 The Prison.rlv,4
level_2_5 = 306 Compression Method 1.rlv,1
level_2_6 = 307 Jump Down.rlv,15
level_2_7 = 308 Lemmings Search For Treasure.rlv,7
level_2_8 = 309 Perseverance.rlv,5
level_2_9 = 310 Izzie Wizzie Lemmings Get Busy.rlv,6
level_2_10 = 311 The Ascending Pillar Scenario.rlv,6
level_2_11 = 312 Livin On The Edge.rlv,11
level_2_12 = 313 Walk Through Here But Cautiously.rlv,12
level_2_13 = 314 Value Each Moment.rlv,13
level_2_14 = 315 What An AWESOME Level.rlv,19
level_2_15 = 316 Umbrella Land.rlv,13
level_2_16 = 317 Lunch Time.rlv,8
level_2_17 = 318 Tribute to MC Escher.rlv,0
level_2_18 = 319 Bomboozal.rlv,1
level_2_19 = 320 Fall And No Life.rlv,2
level_2_20 = 321 Feel The Heat.rlv,8
level_2_21 = 322 Come On Over to My Place.rlv,9
level_2_22 = 323 King of the Castle.rlv,10
level_2_23 = 324 Keep All Enemies Out.rlv,16
level_2_24 = 325 Watch Right And Left.rlv,7
level_2_25 = 326 Triple Trouble.rlv,5
level_2_26 = 327 Watch Your Fingertip.rlv,1
level_2_27 = 328 Watch Right or Left.rlv,0
level_2_28 = 329 How Do I Dig Out a Path.rlv,4
level_2_29 = 330 We All Fall Down.rlv,7

# Rating 3 - Mayhem

level_3_0 = 401 Let's Get Together.rlv,7
level_3_1 = 402 The Boiler Room.rlv,5
level_3_2 = 403 It's Hero Time.rlv,3
level_3_3 = 404 The Crossroads.rlv,9
level_3_4 = 405 Down Along Up in That Order.rlv,4
level_3_5 = 406 Over The Wall.rlv,1
level_3_6 = 407 Poles Apart.rlv,0
level_3_7 = 408 Last One Out is a Rotten Egg.rlv,4
level_3_8 = 409 Twins.rlv,5
level_3_9 = 410 Dangerous Balcony.rlv,6
level_3_10 = 411 We All Fall Down.rlv,8
level_3_11 = 412 The Other Side.rlv,9
level_3_12 = 413 The Great Lemming Caper.rlv,10
level_3_13 = 414 Climb and Fall Fall and Climb.rlv,16
level_3_14 = 415 Two Ponds.rlv,7
level_3_15 = 416 Just a Minute.rlv,5
level_3_16 = 417 Stepping Stones.rlv,1
level_3_17 = 418 Two Different Worlds.rlv,0
level_3_18 = 419 Time to Get Up.rlv,4
level_3_19 = 420 No Added Colours or Lemmings.rlv,7
level_3_20 = 421 With A Twist of Lemming Please.rlv,6
level_3_21 = 422 A Beast II of a Level.rlv,20
level_3_22 = 423 A Group of Entrances.rlv,12
level_3_23 = 424 All or Nothing.rlv,15
level_3_24 = 425 Have a Nice Day.rlv,4
level_3_25 = 426 Lemming Eater.rlv,13
level_3_26 = 427 Just a Minute (Part II).rlv,8
level_3_27 = 428 Leftovers Are Not Always a Waste.rlv,0
level_3_28 = 429 No Hurry Relax.rlv,1
level_3_29 = 430 Lemmings Ark.rlv,2

# Rating 4 - Present

level_4_0 = 601 Natural Life.rlv,8
level_4_1 = 602 Don't Leave My Lemmings.rlv,9
level_4_2 = 603 Let Me Get Out Of Here.rlv,10
level_4_3 = 604 Lemmings Standing on the Earth.rlv,16
level_4_4 = 605 Darkness of the Royal Family.rlv,7
level_4_5 = 606 No Time For a Detour.rlv,5
level_4_6 = 607 Everyone Turn Left.rlv,1
level_4_7 = 608 Libra (Part Two).rlv,0
level_4_8 = 609 Fix The Road Quick.rlv,4
level_4_9 = 610 Where Are You Heading.rlv,0
level_4_10 = 611 Field Athletics.rlv,7
level_4_11 = 612 Balance Beam.rlv,5
level_4_12 = 613 Watch Your Step (Part Two).rlv,3
level_4_13 = 614 Like An Overflowing Wave.rlv,6
level_4_14 = 615 Evil Whisper.rlv,4
level_4_15 = 616 A Trap is a Trap.rlv,13
level_4_16 = 617 Electric Circuit.rlv,0
level_4_17 = 618 King of Lemmings.rlv,7
level_4_18 = 619 Acrophobia.rlv,5
level_4_19 = 620 Lemmings-preying Iron Plate.rlv,6
level_4_20 = 621 Use Your Brain Better.rlv,9
level_4_21 = 622 None Title.rlv,11
level_4_22 = 623 Precarious Oasis.rlv,12
level_4_23 = 624 Everyone's A Hard Nut.rlv,13
level_4_24 = 625 Underground City.rlv,4
level_4_25 = 626 Pitfall.rlv,0
level_4_26 = 627 Try Anything Once.rlv,8
level_4_27 = 628 Which One Are You Trying To Get.rlv,3
level_4_28 = 629 Private Room Available.rlv,1
level_4_29 = 630 Final Impediment.rlv,2

# Rating 5 - Sunsoft

level_5_0 = 701 Rules To Fall.rlv,7
level_5_1 = 702 Inside The Bone.rlv,5
level_5_2 = 703 Anxiety.rlv,3
level_5_3 = 704 Train Your Body.rlv,9
level_5_4 = 705 Watch Your Step.rlv,4
level_5_5 = 706 Libra.rlv,1
level_5_6 = 707 Everyone Turn Left (Part Two).rlv,0
level_5_7 = 708 Is This A Circus.rlv,4
level_5_8 = 709 Evacuating a Coal Mine.rlv,5
level_5_9 = 710 Spiral Staircase.rlv,6
level_5_10 = 711 Turn Around And Look.rlv,15
level_5_11 = 712 Water Processing Plant.rlv,11
level_5_12 = 713 Doomsday.rlv,12
level_5_13 = 714 No World Without You.rlv,13
level_5_14 = 715 Exodus.rlv,4
level_5_15 = 716 Here is Mr Lemming's House.rlv,13
level_5_16 = 717 Cave Quest.rlv,8
level_5_17 = 718 SUNSOFT Special.rlv,21
level_5_18 = 719 Let's Go Camping.rlv,1
level_5_19 = 720 Haunted Botanical Garden.rlv,2
level_5_20 = 721 Be Sure To Be a Builder.rlv,8
level_5_21 = 722 Watch Right or Left (Part Two).rlv,9
level_5_22 = 723 Move On in Two Separate Groups.rlv,15
level_5_23 = 724 Out Away From The Tune.rlv,16
level_5_24 = 725 Stray Sheep.rlv,7
level_5_25 = 726 Just A Minute (Part Three).rlv,5
level_5_26 = 727 Two Heads Are Better.rlv,1
level_5_27 = 728 The Gate Trap Lemmings.rlv,0
level_5_28 = 729 I Am AT.rlv,14
level_5_29 = 730 Fall And No Life (Part Two).rlv,4

# Rating 6 - 2-Player

level_6_0 = 801 There Can Only Be One.rlv,8
level_6_1 = 802 Still Everything To Play For.rlv,9
level_6_2 = 803 In The Thick Of The Fray.rlv,10
level_6_3 = 804 Game On Choose Your Tactics.rlv,16
level_6_4 = 805 Good Game Good Game.rlv,4
level_6_5 = 806 The Rubbish Dump.rlv,5
level_6_6 = 807 And The Winner Is.rlv,1
level_6_7 = 808 Any Chance of a Truce.rlv,0
level_6_8 = 809 Now Use Miners and Climbers.rlv,4
level_6_9 = 810 Joy Joy Joy.rlv,8
level_6_10 = 811 Just For Fun or To The Death.rlv,7
level_6_11 = 812 A Task For Blockers and Bombers.rlv,5
level_6_12 = 813 Crossover Point.rlv,3
level_6_13 = 814 The Passing Place.rlv,9
level_6_14 = 815 Take What You Can When You Can.rlv,4
level_6_15 = 816 The Hammock.rlv,1
level_6_16 = 817 A Task For Blockers and Bomber.rlv,3
level_6_17 = 818 Islands in the Sky.rlv,7
level_6_18 = 819 May The Craftiest Player Win.rlv,5
level_6_19 = 820 We're in This One Together.rlv,6

