# animation types
# 0 - don't animate
# 1 - animate continuously
# 2 - trap - animate on trigger - else show first pic
# 3 - entrance animation: animate once at level start

# object types
# 0  - passive
# 1  - turn left
# 2  - turn right
# 3  - no digging to the left
# 4  - no digging to the right
# 5  - trap that makes lemmings drown (water/quick sand/mud)
# 6  - trap that removes lemming
# 7  - trap that triggers lemming death animation
# 8  - exit
# 9  - steel
# 32 - entrance

bgColor   = 0x000030
debrisColor = 0xf0f0f0
particleColor  = 0xffffff,0x4040e0,0x00b000,0xf0d0d0,0xf0f000,0xf02020,0x808080,0xe08020,0xf0f0f0,0xa0c0d0,0x70a0b0,0x4080a0,0x206080,0x004050,0x504040,0x000000

tiles = 55
steelTiles = 51,52,53,54

# entrance - animate once
frames_0       = 10
speed_0        = 2
anim_0         = 3
type_0         = 32
maskOffsetX_0  = 0
maskOffsetY_0  = 0
sound_0        = 5

# exit - always animate
frames_1       = 6
speed_1        = 2
anim_1         = 1
type_1         = 8
maskOffsetX_1  = 0
maskOffsetY_1  = 2
sound_1        = 14

# water - always animate
frames_2      = 8
speed_2       = 2
anim_2        = 1
type_2        = 5
maskOffsetX_2 = 0
maskOffsetY_2 = 0
sound_2       = 17