/*
 * Copyright 2014 Ryan Sakowski.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package lemmini.gui;

import java.awt.Frame;
import java.awt.Toolkit;

import javax.swing.JComboBox;
import javax.swing.JDialog;

import lemmini.LemminiFrame;
import lemmini.game.Core;
import lemmini.game.GameController;
import lemmini.game.GameController.ExitSoundOption;
import lemmini.game.GameController.MenuThemeOption;
import lemmini.sound.Music;

/**
 *
 * @author Ryan Sakowski
 */
public class OptionsDialog extends JDialog {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form OptionsDialog
     * @param parent
     * @param modal
     */
    public OptionsDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSound = new javax.swing.JPanel();
        jCheckBoxEnableMusic = new javax.swing.JCheckBox();
        jLabelMusicVolume = new javax.swing.JLabel();
        jSliderMusicVolume = new javax.swing.JSlider();
        jCheckBoxEnableSound = new javax.swing.JCheckBox();
        jLabelSoundVolume = new javax.swing.JLabel();
        jSliderSoundVolume = new javax.swing.JSlider();
        jLabelMixer = new javax.swing.JLabel();
        jComboBoxMixer = new JComboBox<String>(GameController.sound.getMixers());
        jLabelExitSound = new javax.swing.JLabel();
        jRadioButtonYippee = new javax.swing.JRadioButton();
        jRadioButtonBoing = new javax.swing.JRadioButton();
        jRadioButtonAuto = new javax.swing.JRadioButton();
        exitSoundGroup = new javax.swing.ButtonGroup();
        jLabelMenuTheme = new javax.swing.JLabel();
        jRadioButtonAmigaTheme = new javax.swing.JRadioButton();
        jRadioButtonWinLemmTheme = new javax.swing.JRadioButton();
        menuThemeGroup = new javax.swing.ButtonGroup();
        jPanelGraphics = new javax.swing.JPanel();
        jCheckBoxBilinear = new javax.swing.JCheckBox();
        jPanelClassicMode = new javax.swing.JPanel();
        jPanelControlScheme = new javax.swing.JPanel();
        jPanelMisc = new javax.swing.JPanel();
        jPanelReplays = new javax.swing.JPanel();
        jCheckBoxAdvanced = new javax.swing.JCheckBox();
        jCheckBoxClassicCursor = new javax.swing.JCheckBox();
        jCheckBoxSwap = new javax.swing.JCheckBox();
        jCheckBoxFaster = new javax.swing.JCheckBox();
        jCheckBoxPauseStopsFastForward = new javax.swing.JCheckBox();
        jCheckBoxNoPercentages = new javax.swing.JCheckBox();
        jCheckBoxReplayScroll = new javax.swing.JCheckBox();
        jCheckBoxUnpauseOnAssignment = new javax.swing.JCheckBox();
        jCheckBoxTimedBombers = new javax.swing.JCheckBox();
        jCheckBoxUnlockAllLevels = new javax.swing.JCheckBox();
        jCheckBoxEnableScrollWheel = new javax.swing.JCheckBox();
        jCheckBoxEnableFrameStepping = new javax.swing.JCheckBox();
        jCheckBoxVisualSfx = new javax.swing.JCheckBox();
        //jCheckBoxFullScreen = new javax.swing.JCheckBox();
        jCheckBoxEnhancedStatus = new javax.swing.JCheckBox();
        jCheckBoxShowLevelName = new javax.swing.JCheckBox();
        jCheckBoxEnhancedIconBar = new javax.swing.JCheckBox();
        jCheckBoxIconLabels = new javax.swing.JCheckBox();
        jCheckBoxFullColorMinimap = new javax.swing.JCheckBox();
        jCheckBoxClassicScroller = new javax.swing.JCheckBox();
        jCheckBoxShowMenuBar = new javax.swing.JCheckBox();
        jCheckBoxAutoSaveReplays = new javax.swing.JCheckBox();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setIconImage(Toolkit.getDefaultToolkit().getImage(LemminiFrame.class.getClassLoader().getResource("icon_256.png")));
        setResizable(false);

        jPanelSound.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sound", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jCheckBoxEnableMusic.setSelected(GameController.isOptionEnabled(GameController.Option.MUSIC_ON));
        jCheckBoxEnableMusic.setText("Enable Music");

        jLabelMusicVolume.setLabelFor(jSliderMusicVolume);
        jLabelMusicVolume.setText("Music Volume");

        jSliderMusicVolume.setMajorTickSpacing(10);
        jSliderMusicVolume.setMaximum(200);
        jSliderMusicVolume.setPaintTicks(true);
        jSliderMusicVolume.setValue((int) (100 * GameController.getMusicGain()));

        jCheckBoxEnableSound.setSelected(GameController.isOptionEnabled(GameController.Option.SOUND_ON));
        jCheckBoxEnableSound.setText("Enable Sound Effects");

        jLabelSoundVolume.setLabelFor(jSliderSoundVolume);
        jLabelSoundVolume.setText("Sound Volume");

        jSliderSoundVolume.setMajorTickSpacing(10);
        jSliderSoundVolume.setMaximum(200);
        jSliderSoundVolume.setPaintTicks(true);
        jSliderSoundVolume.setValue((int) (100 * GameController.getSoundGain()));

        jLabelMixer.setText("SFX Mixer");

        jCheckBoxVisualSfx.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.VISUAL_SFX));
        jCheckBoxVisualSfx.setText("Enable Visual SFX");

        // Radio group for Exit sound
        jLabelExitSound.setText("Exit Sound");
        jRadioButtonYippee.setText("Yippee");
        jRadioButtonBoing.setText("Boing");
        jRadioButtonAuto.setText("Auto");

        exitSoundGroup.add(jRadioButtonYippee);
        exitSoundGroup.add(jRadioButtonBoing);
        exitSoundGroup.add(jRadioButtonAuto);

        ExitSoundOption exitSoundOption = GameController.getExitSoundOption();
        switch (exitSoundOption) {
            case YIPPEE:
                jRadioButtonYippee.setSelected(true);
                break;
            case BOING:
                jRadioButtonBoing.setSelected(true);
                break;
            case AUTO:
            default:
                jRadioButtonAuto.setSelected(true);
                break;
        }

//        jCheckBoxFullScreen.setSelected(GameController.isOptionEnabled(GameController.RetroLemminiOption.FULL_SCREEN));
//        jCheckBoxFullScreen.setText("Full Screen");

        jCheckBoxEnhancedStatus.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.ENHANCED_STATUS));
        jCheckBoxEnhancedStatus.setText("Enhanced Status Bar");
        jCheckBoxEnhancedStatus.addActionListener(e -> {
            boolean enabled = jCheckBoxEnhancedStatus.isSelected();
            jCheckBoxShowLevelName.setEnabled(enabled);

            if (!enabled) {
                jCheckBoxShowLevelName.setSelected(false);
            }
        });

        jCheckBoxShowLevelName.setEnabled(jCheckBoxEnhancedStatus.isSelected());
        jCheckBoxShowLevelName.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.SHOW_LEVEL_NAME));
        jCheckBoxShowLevelName.setText("Show Level Name on the Status Bar");

        jCheckBoxEnhancedIconBar.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.ENHANCED_ICONBAR));
        jCheckBoxEnhancedIconBar.setText("Enhanced Icon Bar");

        jCheckBoxIconLabels.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.ICON_LABELS));
        jCheckBoxIconLabels.setText("Show Labels on the Icon Bar");
        
        jCheckBoxFullColorMinimap.setSelected(GameController.isOptionEnabled(GameController.RetroLemminiOption.FULL_COLOR_MINIMAP));
        jCheckBoxFullColorMinimap.setText("Full Color Minimap");

        jCheckBoxClassicScroller.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.CLASSIC_SCROLLER));
        jCheckBoxClassicScroller.setText("Classic Scroller");
        jCheckBoxClassicScroller.setToolTipText("Show the classic ticker tape scroller on the title screen");

        jCheckBoxShowMenuBar.setSelected(GameController.isOptionEnabled(GameController.RetroLemminiOption.SHOW_MENU_BAR));
        jCheckBoxShowMenuBar.setText("Show Menu Bar (Ctrl + M)");
        jCheckBoxShowMenuBar.setToolTipText("Show the menu bar at the top of the game window. Use Ctrl + M to toggle visibility at any time");
        
        // Radio group for Exit sound
        jLabelMenuTheme.setText("Menu Theme");
        jRadioButtonAmigaTheme.setText("Amiga");
        jRadioButtonWinLemmTheme.setText("WinLemm");

        menuThemeGroup.add(jRadioButtonAmigaTheme);
        menuThemeGroup.add(jRadioButtonWinLemmTheme);

        MenuThemeOption menuThemeOption = GameController.getMenuThemeOption();
        switch (menuThemeOption) {
            case AMIGA:
            	jRadioButtonAmigaTheme.setSelected(true);
                break;
            case WINLEMM:
            default:
            	jRadioButtonWinLemmTheme.setSelected(true);
                break;
        }

        jComboBoxMixer.setSelectedIndex(GameController.sound.getMixerIdx());

        javax.swing.GroupLayout jPanelSoundLayout = new javax.swing.GroupLayout(jPanelSound);
        jPanelSound.setLayout(jPanelSoundLayout);
        jPanelSoundLayout.setHorizontalGroup(
            jPanelSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSoundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxEnableSound)
                    .addComponent(jCheckBoxEnableMusic)
                    .addComponent(jLabelMusicVolume)
                    .addComponent(jSliderMusicVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSoundVolume)
                    .addComponent(jSliderSoundVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMixer)
                    .addComponent(jComboBoxMixer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxVisualSfx)
                    .addComponent(jLabelExitSound)
                    .addGroup(jPanelSoundLayout.createSequentialGroup()
                            .addComponent(jRadioButtonYippee)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButtonBoing)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButtonAuto))
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSoundLayout.setVerticalGroup(
            jPanelSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxEnableMusic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMusicVolume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderMusicVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 40, 40)
                .addComponent(jCheckBoxEnableSound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxVisualSfx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSoundVolume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderSoundVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 40, 40)
                .addComponent(jLabelMixer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMixer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, 20)
                .addComponent(jLabelExitSound)
                .addGroup(jPanelSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonYippee)
                        .addComponent(jRadioButtonBoing)
                        .addComponent(jRadioButtonAuto)
                        )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );

        jPanelGraphics.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graphics", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jCheckBoxBilinear.setSelected(Core.isBilinear());
        jCheckBoxBilinear.setText("Bilinear Filtering");

        javax.swing.GroupLayout jPanelGraphicsLayout = new javax.swing.GroupLayout(jPanelGraphics);
        jPanelGraphics.setLayout(jPanelGraphicsLayout);
        jPanelGraphicsLayout.setHorizontalGroup(
                jPanelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGraphicsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            //.addComponent(jCheckBoxFullScreen) // BOOKMARK TODO: Yet to be implemented
                            .addComponent(jCheckBoxShowMenuBar)
                            .addComponent(jCheckBoxBilinear)
                            .addComponent(jCheckBoxClassicScroller)
                            .addComponent(jCheckBoxEnhancedStatus)
                            .addComponent(jCheckBoxShowLevelName)
                            .addComponent(jCheckBoxEnhancedIconBar)
                            .addComponent(jCheckBoxIconLabels)
                            .addComponent(jCheckBoxFullColorMinimap)
                            .addComponent(jLabelMenuTheme)
                            .addGroup(jPanelGraphicsLayout.createSequentialGroup()
                                    .addComponent(jRadioButtonAmigaTheme)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButtonWinLemmTheme)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            )
                        )
            );
        jPanelGraphicsLayout.setVerticalGroup(
            jPanelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGraphicsLayout.createSequentialGroup()
                .addContainerGap()
//                .addComponent(jCheckBoxFullScreen)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) // BOOKMARK TODO: Yet to be implemented
                .addComponent(jCheckBoxShowMenuBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxBilinear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxClassicScroller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEnhancedStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowLevelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEnhancedIconBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxIconLabels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxFullColorMinimap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMenuTheme)
                .addGroup(jPanelGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonAmigaTheme)
                        .addComponent(jRadioButtonWinLemmTheme)
                        )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );

        jPanelReplays.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Replays", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jCheckBoxAutoSaveReplays.setSelected(GameController.isOptionEnabled(GameController.RetroLemminiOption.AUTOSAVE_REPLAYS));
        jCheckBoxAutoSaveReplays.setText("Auto-Save Successful Replays");
        jCheckBoxAutoSaveReplays.setToolTipText("Automatically saves replays for succesfully-completed levels to 'resources/replays/'");

        javax.swing.GroupLayout jPanelReplaysLayout = new javax.swing.GroupLayout(jPanelReplays);
        jPanelReplays.setLayout(jPanelReplaysLayout);
        jPanelReplaysLayout.setHorizontalGroup(
                jPanelReplaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReplaysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReplaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAutoSaveReplays)
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReplaysLayout.setVerticalGroup(
                jPanelReplaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReplaysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxAutoSaveReplays)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );

        jPanelClassicMode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Classic Mode", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        
        jCheckBoxAdvanced.setSelected(GameController.isOptionEnabled(GameController.Option.ADVANCED_SELECT));
        jCheckBoxAdvanced.setText("Advanced Select");
        jCheckBoxAdvanced.setToolTipText("Hold directional keys to select only Lemmings going in that same direction. Hold Up to select only Walkers.");
        
        jCheckBoxTimedBombers.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.TIMED_BOMBERS));
        jCheckBoxTimedBombers.setText("Enable 5 second timed bombers");
        
        jCheckBoxEnableFrameStepping.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.ENABLE_FRAME_STEPPING));
        jCheckBoxEnableFrameStepping.setText("Enable Frame Stepping");
        jCheckBoxEnableFrameStepping.setToolTipText("Enable advancing the game by a single frame when paused.");
        
        javax.swing.GroupLayout jPanelClassicModeLayout = new javax.swing.GroupLayout(jPanelClassicMode);
        jPanelClassicMode.setLayout(jPanelClassicModeLayout);
        jPanelClassicModeLayout.setHorizontalGroup(
        		jPanelClassicModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClassicModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClassicModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAdvanced)
                    .addComponent(jCheckBoxTimedBombers)
                    .addComponent(jCheckBoxEnableFrameStepping)
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClassicModeLayout.setVerticalGroup(
        		jPanelClassicModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClassicModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxAdvanced)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxTimedBombers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEnableFrameStepping)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        jPanelControlScheme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Scheme", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jCheckBoxClassicCursor.setSelected(GameController.isOptionEnabled(GameController.Option.CLASSIC_CURSOR));
        jCheckBoxClassicCursor.setText("Classic Cursor");
        jCheckBoxClassicCursor.setToolTipText("The Standard Cursor centers around the selected lemming. The Classic Cursor follows the mouse.");
        
        jCheckBoxSwap.setSelected(GameController.isOptionEnabled(GameController.Option.SWAP_BUTTONS));
        jCheckBoxSwap.setText("Swap Middle/Right Mouse Buttons");
        jCheckBoxSwap.setToolTipText("Swap which button pauses the game and which increases the scroll speed of the viewport.");

        jCheckBoxFaster.setSelected(GameController.isOptionEnabled(GameController.Option.FASTER_FAST_FORWARD));
        jCheckBoxFaster.setText("Double Fast-Forward Speed");
        jCheckBoxFaster.setToolTipText("Standard Fast-Forward is 3x faster than normal. Doubled Fast-Forward is 6x faster than normal.");

        jCheckBoxPauseStopsFastForward.setSelected(GameController.isOptionEnabled(GameController.Option.PAUSE_STOPS_FAST_FORWARD));
        jCheckBoxPauseStopsFastForward.setText("Stop Fast-Forward When Pausing");
        
        jCheckBoxReplayScroll.setSelected(GameController.isOptionEnabled(GameController.Option.REPLAY_SCROLL));
        jCheckBoxReplayScroll.setText("Scroll Level During Replay");

        jCheckBoxUnpauseOnAssignment.setSelected(GameController.isOptionEnabled(GameController.Option.UNPAUSE_ON_ASSIGNMENT));
        jCheckBoxUnpauseOnAssignment.setText("Unpause After Assigning Skill");
        
        jCheckBoxEnableScrollWheel.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.ENABLE_SCROLL_WHEEL));
        jCheckBoxEnableScrollWheel.setText("Enable Scroll Wheel");
        jCheckBoxEnableScrollWheel.setToolTipText("Use the mouse scroll wheel to change the selected skill.");
        
        javax.swing.GroupLayout jPanelControlSchemeLayout = new javax.swing.GroupLayout(jPanelControlScheme);
        jPanelControlScheme.setLayout(jPanelControlSchemeLayout);
        jPanelControlSchemeLayout.setHorizontalGroup(
        		jPanelControlSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlSchemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addComponent(jCheckBoxClassicCursor)
                    .addComponent(jCheckBoxSwap)
                    .addComponent(jCheckBoxEnableScrollWheel)
                    .addComponent(jCheckBoxFaster)
                    .addComponent(jCheckBoxPauseStopsFastForward)
                    .addComponent(jCheckBoxUnpauseOnAssignment)
                    .addComponent(jCheckBoxReplayScroll)
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelControlSchemeLayout.setVerticalGroup(
        		jPanelControlSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlSchemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxClassicCursor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSwap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEnableScrollWheel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPauseStopsFastForward)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxUnpauseOnAssignment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxReplayScroll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        jPanelMisc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Miscellaneous", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jCheckBoxNoPercentages.setSelected(!GameController.isOptionEnabled(GameController.Option.NO_PERCENTAGES));
        jCheckBoxNoPercentages.setText("Use Percentage For Rescue Count");

        jCheckBoxUnlockAllLevels.setSelected(GameController.isOptionEnabled(GameController.SLTooOption.UNLOCK_ALL_LEVELS));
        jCheckBoxUnlockAllLevels.setText("Unlock all levels");
        jCheckBoxUnlockAllLevels.setToolTipText("All access to all levels, without having to complete previous ones.");

        javax.swing.GroupLayout jPanelMiscLayout = new javax.swing.GroupLayout(jPanelMisc);
        jPanelMisc.setLayout(jPanelMiscLayout);
        jPanelMiscLayout.setHorizontalGroup(
            jPanelMiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiscLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxNoPercentages)
                    .addComponent(jCheckBoxUnlockAllLevels)
                    )
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMiscLayout.setVerticalGroup(
            jPanelMiscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiscLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxNoPercentages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxUnlockAllLevels)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonOK.setText("Save and Close");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)
                    )
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelGraphics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelReplays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addComponent(jPanelClassicMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        	.addComponent(jPanelControlScheme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        	.addComponent(jPanelMisc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    )
                )
                .addContainerGap()
            )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelReplays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    )
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelClassicMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelControlScheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelMisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    )
                )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK)
                )
                .addContainerGap()
            )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        applyChanges();
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void applyChanges() {
        // set all game settings based on GUI options first
        // apply sound settings
        GameController.setOption(GameController.Option.MUSIC_ON, jCheckBoxEnableMusic.isSelected());
        if (GameController.getLevel() != null) {
            if (GameController.isOptionEnabled(GameController.Option.MUSIC_ON)
                    && GameController.getGameState() == GameController.State.LEVEL) {
                Music.play();
            } else {
                Music.stop();
            }
        }
        GameController.setMusicGain(jSliderMusicVolume.getValue() / 100.0);
        GameController.setOption(GameController.Option.SOUND_ON, jCheckBoxEnableSound.isSelected());
        GameController.setSoundGain(jSliderSoundVolume.getValue() / 100.0);
        GameController.sound.setMixerIdx(jComboBoxMixer.getSelectedIndex());
        // apply exit sound setting
        GameController.setExitSoundOption(
                jRadioButtonYippee.isSelected() ? GameController.ExitSoundOption.YIPPEE :
                jRadioButtonBoing.isSelected() ? GameController.ExitSoundOption.BOING :
                GameController.ExitSoundOption.AUTO
            );
        // apply graphics settings
        Core.setBilinear(jCheckBoxBilinear.isSelected());
        GameController.setOption(GameController.Option.CLASSIC_CURSOR, jCheckBoxClassicCursor.isSelected());
        //GameController.setOption(GameController.RetroLemminiOption.FULL_SCREEN, jCheckBoxFullScreen.isSelected());
        GameController.setOption(GameController.SLTooOption.ENHANCED_STATUS, jCheckBoxEnhancedStatus.isSelected());
        GameController.setOption(GameController.SLTooOption.SHOW_LEVEL_NAME, jCheckBoxShowLevelName.isSelected());
        GameController.setOption(GameController.SLTooOption.ENHANCED_ICONBAR, jCheckBoxEnhancedIconBar.isSelected());
        GameController.setOption(GameController.SLTooOption.ICON_LABELS, jCheckBoxIconLabels.isSelected());
        GameController.setOption(GameController.RetroLemminiOption.FULL_COLOR_MINIMAP, jCheckBoxFullColorMinimap.isSelected());
        GameController.setOption(GameController.SLTooOption.CLASSIC_SCROLLER, jCheckBoxClassicScroller.isSelected());
        // apply menu theme setting
        GameController.setMenuThemeOption(
                jRadioButtonAmigaTheme.isSelected() ? GameController.MenuThemeOption.AMIGA :
                GameController.MenuThemeOption.WINLEMM
            );
        // apply replay settings
        GameController.setOption(GameController.RetroLemminiOption.AUTOSAVE_REPLAYS, jCheckBoxAutoSaveReplays.isSelected());
        GameController.setOption(GameController.RetroLemminiOption.SHOW_MENU_BAR, jCheckBoxShowMenuBar.isSelected());
        // apply miscellaneous settings
        GameController.setOption(GameController.Option.ADVANCED_SELECT, jCheckBoxAdvanced.isSelected());
        GameController.setOption(GameController.Option.SWAP_BUTTONS, jCheckBoxSwap.isSelected());
        GameController.setOption(GameController.Option.FASTER_FAST_FORWARD, jCheckBoxFaster.isSelected());
        GameController.setOption(GameController.Option.PAUSE_STOPS_FAST_FORWARD, jCheckBoxPauseStopsFastForward.isSelected());
        GameController.setOption(GameController.Option.NO_PERCENTAGES, !jCheckBoxNoPercentages.isSelected());
        GameController.setOption(GameController.Option.REPLAY_SCROLL, jCheckBoxReplayScroll.isSelected());
        GameController.setOption(GameController.Option.UNPAUSE_ON_ASSIGNMENT, jCheckBoxUnpauseOnAssignment.isSelected());
        GameController.setOption(GameController.SLTooOption.TIMED_BOMBERS, jCheckBoxTimedBombers.isSelected());
        GameController.setOption(GameController.SLTooOption.UNLOCK_ALL_LEVELS, jCheckBoxUnlockAllLevels.isSelected());
        GameController.setOption(GameController.SLTooOption.ENABLE_SCROLL_WHEEL, jCheckBoxEnableScrollWheel.isSelected());
        GameController.setOption(GameController.SLTooOption.ENABLE_FRAME_STEPPING, jCheckBoxEnableFrameStepping.isSelected());
        GameController.setOption(GameController.SLTooOption.VISUAL_SFX, jCheckBoxVisualSfx.isSelected());

        //then commit all those settings to disk
        Core.saveSettings();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxAdvanced;
    private javax.swing.JCheckBox jCheckBoxBilinear;
    private javax.swing.JCheckBox jCheckBoxClassicCursor;
    private javax.swing.JCheckBox jCheckBoxEnableMusic;
    private javax.swing.JCheckBox jCheckBoxEnableSound;
    private javax.swing.JCheckBox jCheckBoxFaster;
    private javax.swing.JCheckBox jCheckBoxNoPercentages;
    private javax.swing.JCheckBox jCheckBoxPauseStopsFastForward;
    private javax.swing.JCheckBox jCheckBoxReplayScroll;
    private javax.swing.JCheckBox jCheckBoxSwap;
    private javax.swing.JCheckBox jCheckBoxUnpauseOnAssignment;
    private javax.swing.JCheckBox jCheckBoxTimedBombers;
    private javax.swing.JCheckBox jCheckBoxUnlockAllLevels;
    private javax.swing.JCheckBox jCheckBoxEnableScrollWheel;
    private javax.swing.JCheckBox jCheckBoxEnableFrameStepping;
    private javax.swing.JCheckBox jCheckBoxVisualSfx;
    //private javax.swing.JCheckBox jCheckBoxFullScreen;
    private javax.swing.JCheckBox jCheckBoxEnhancedStatus;
    private javax.swing.JCheckBox jCheckBoxShowLevelName;
    private javax.swing.JCheckBox jCheckBoxEnhancedIconBar;
    private javax.swing.JCheckBox jCheckBoxIconLabels;
    private javax.swing.JCheckBox jCheckBoxFullColorMinimap;
    private javax.swing.JCheckBox jCheckBoxClassicScroller;
    private javax.swing.JCheckBox jCheckBoxShowMenuBar;
    private javax.swing.JCheckBox jCheckBoxAutoSaveReplays;
    private javax.swing.JComboBox<String> jComboBoxMixer;
    private javax.swing.JLabel jLabelMixer;
    private javax.swing.JLabel jLabelMusicVolume;
    private javax.swing.JLabel jLabelSoundVolume;
    private javax.swing.JLabel jLabelExitSound;
    private javax.swing.JRadioButton jRadioButtonYippee;
    private javax.swing.JRadioButton jRadioButtonBoing;
    private javax.swing.JRadioButton jRadioButtonAuto;
    private javax.swing.ButtonGroup exitSoundGroup;
    private javax.swing.JLabel jLabelMenuTheme;
    private javax.swing.JRadioButton jRadioButtonAmigaTheme;
    private javax.swing.JRadioButton jRadioButtonWinLemmTheme;
    private javax.swing.ButtonGroup menuThemeGroup;
    private javax.swing.JPanel jPanelGraphics;
    private javax.swing.JPanel jPanelClassicMode;
    private javax.swing.JPanel jPanelControlScheme;
    private javax.swing.JPanel jPanelMisc;
    private javax.swing.JPanel jPanelReplays;
    private javax.swing.JPanel jPanelSound;
    private javax.swing.JSlider jSliderMusicVolume;
    private javax.swing.JSlider jSliderSoundVolume;
    // End of variables declaration//GEN-END:variables
}
