name = NES Lemmings

codeSeed = SUERBRLIAF


# Music selection
music_0 = nes/orig_01cancan_nes.ogg
music_1 = nes/orig_03tim2_nes.ogg
music_2 = nes/orig_04lemming2_nes.ogg
music_3 = nes/orig_06tim3_nes.ogg
music_4 = nes/orig_09tim6_nes.ogg
music_5 = nes/orig_11_tim7_nes.ogg
music_6 = nes/orig_12tim9_nes.ogg
music_7 = nes/orig_14tim10_nes.ogg

# Groups
level_0 = NES

# Levels: name, music ID

# Rating 0 - NES

level_0_0 = 101 We All Fall Down.rlv,0
level_0_1 = 102 Origins and Lemmings.rlv,1
level_0_2 = 103 Danger The Bridge Is Out.rlv,2
level_0_3 = 104 Do Not Do Anything Too Hasty.rlv,3
level_0_4 = 105 Lemmings Lemmings Everywhere.rlv,4
level_0_5 = 106 Lemming And Lime.rlv,5
level_0_6 = 201 A Bag Of Lemming Drops.rlv,6
level_0_7 = 202 Lemming I Scream.rlv,7
level_0_8 = 203 Iced Lemming.rlv,8
level_0_9 = 204 The Crankshaft.rlv,9
level_0_10 = 205 Lemming Good Fun.rlv,10
level_0_11 = 206 Lemming Sanctuary In Sight.rlv,11
level_0_12 = 301 Roman In The Ruins.rlv,12
level_0_13 = 302 Up The Wooden Hill.rlv,13
level_0_14 = 303 A Spot Of Bother.rlv,14
level_0_15 = 304 On The Spiders Web.rlv,15
level_0_16 = 305 Just Drop In.rlv,16
level_0_17 = 306 Arctic Lemmings.rlv,17
level_0_18 = 307 Come To Lemming County.rlv,18
level_0_19 = 401 There Must Be More To Life.rlv,19
level_0_20 = 402 Pass Me That Lemming.rlv,20
level_0_21 = 403 This Lemmings Faulty.rlv,21
level_0_22 = 404 Hello John Got A New Lemming.rlv,22
level_0_23 = 405 My Word What A Lemming.rlv,23
level_0_24 = 406 A Free Lemming In Every Pack.rlv,24
level_0_25 = 407 Is That Lemming Licensed.rlv,25
level_0_26 = 408 How Much More Can You Take.rlv,26

