name = Lemmings 2 The Tribes Classic Remake by PacGuy765
#path = Lemmings 2
maxFallDistance = 126

codeSeed = AQUCMZOMAU

# music selection
music_0  = l2\lem2classic.mod


# levels of difficulty
level_0 = Classic

#Levels: name, code, music id

# Level 0 - Classic

# Classic 1 - Do You Remember?
classic_0 = 01 Do You Remember.rlv,0
# Classic 2 - Mr Lemmy Lives Next Door
classic_1 = 02 Mr Lemmy Lives Next Door.rlv,0
# Classic 3 - LEMTRIS
classic_2 = 03 LEMTRIS.rlv,0
# Classic 4 - Tension Sheet, Good Idea
classic_3 = 04 Tension Sheet Good Idea.rlv,0
# Classic 5 - The Magnificent Severn
classic_4 = 05 The Magnificent Severn.rlv,0
# Classic 6 - The Starry Threshold
classic_5 = 06 The Starry Threshold.rlv,0
# Classic 7 - So close but so far away
classic_6 = 07 So close but so far away.rlv,0
# Classic 8 - The Secret of LEMH
classic_7 = 08 The Secret of LEMH.rlv,0
# Classic 9 - Flying The Mad Pursuit
classic_8 = 09 Flying The Mad Pursuit.rlv,0
# Classic 10 - What's it like up there?
classic_9 = 10 What's it like up there.rlv,0