name = Lemmings 2 The Tribes
#remade by PacGuy765 from the original DMA L2 levels

maxFallDistance = 126

codeSeed = AQUCMZOMAU

# music selection
music_0  = l2\lem2classic.mod


# levels of difficulty
level_0 = Classic Tribe

#Levels: name, code, music id

level_0_0 = 01 Do You Remember.rlv,0
level_0_1 = 02 Mr Lemmy Lives Next Door.rlv,0
level_0_2 = 03 LEMTRIS.rlv,0
level_0_3 = 04 Tension Sheet Good Idea.rlv,0
level_0_4 = 05 The Magnificent Severn.rlv,0
level_0_5 = 06 The Starry Threshold.rlv,0
level_0_6 = 07 So close but so far away.rlv,0
level_0_7 = 08 The Secret of LEMH.rlv,0
level_0_8 = 09 Flying The Mad Pursuit.rlv,0
level_0_9 = 10 What's it like up there.rlv,0