# based on http://www.deveria.com/alexis/lemmings/lemmings/amigacodes.html
# and http://home.wanadoo.nl/lemmings-solution/index2.html
# and http://www.deinonych.com/lemmings/lemm1fun_walk.shtml

name = SEGA Lemmings

codeSeed = SEGALEMSOK

# music selection
music_0 = sega/orig_01-cancansega.ogg
music_1 = sega/orig_02-lemming1sega.ogg
music_2 = sega/orig_03-tim2sega.ogg
music_3 = sega/orig_04-lemming2sega.ogg
music_4 = sega/orig_05-tim8sega.ogg
music_5 = sega/orig_06-tim3sega.ogg
music_6 = sega/orig_07-tim5sega.ogg
music_7 = sega/orig_08-doggiesega.ogg
music_8 = sega/orig_09-tim6sega.ogg
music_9 = sega/orig_10-lemmings3sega.ogg
music_10 = sega/orig_11-tim7sega.ogg
music_11 = sega/orig_12-tim9sega.ogg
music_12 = sega/orig_13-tim1sega.ogg
music_13 = sega/orig_14-tim10sega.ogg
music_14 = sega/orig_15-tim4sega.ogg
music_15 = sega/orig_16-tenlemmssega.ogg
music_16 = sega/orig_17-mountainsega.ogg



# ratings
level_0 = Extra Levels

# Levels: name, music ID
# Rating 0 - Level

# Level 1 Sega One (Fun)
level_0_0 = 01 Sega One (Fun).rlv,2
# Level 2 Sega Two (Fun)
level_0_1 = 02 Sega Two (Fun).rlv,8
# Level 3 Sixes Not
level_0_2 = 03 Sixes Not.rlv,3
# Level 4 Sega Three (Tricky)
level_0_3 = 04 Sega Three (Tricky).rlv,7
# Level 5 Sega Four (Taxing)
level_0_4 = 05 Sega Four (Taxing).rlv,3
# Level 6 Sega Five (Taxing)
level_0_5 = 06 Sega Five (Taxing).rlv,12
# Level 7 Sega one (Mayhem)
level_0_6 = 07 Sega one (Mayhem).rlv,8
# Level 8 Sega Two (Mayhem)
level_0_7 = 08 Sega Two (Mayhem).rlv,11
# Level 9 Sega Three (Mayhem)
level_0_8 = 09 Sega Three (Mayhem).rlv,12
# Level 10 Stepping Stones
level_0_9 = 10 Stepping Stones.rlv,15
# Level 11 Sega Four (Mayhem)
level_0_10 = 11 Sega Four (Mayhem).rlv,0
# Level 12 Sega Five (Mayhem)
level_0_11 = 12 Sega Five (Mayhem).rlv,11

