name = Lemmings Extra

codeSeed = EXTRALEMMS


# Music selection
music_0 = lemming1.mod
music_1 = lemming2.mod
music_2 = lemming3.mod
music_3 = mountain.mod
music_4 = tenlemms.mod
music_5 = cancan.mod
music_6 = tim1.mod
music_7 = tim2.mod
music_8 = tim3.mod
music_9 = tim4.mod
music_10 = doggie.mod
music_11 = tim5.mod
music_12 = tim6.mod
music_13 = tim7.mod
music_14 = tim8.mod
music_15 = tim9.mod
music_16 = tim10.mod

# Groups
level_0 = Save The Lemmings (The COVOX Levels)
level_1 = Lemmings Companion (The Prima Publishing Levels)
level_2 = DMA Bonus Levels

# Levels: name, music ID

# Rating 0 - Save The Lemmings (The COVOX Levels)

level_0_0 = 101 The Covox Level.rlv,0
level_0_1 = 102 Bridge Away.rlv,1
level_0_2 = 103 Animal or Vegetable.rlv,2
level_0_3 = 104 Lots of Steel Crates.rlv,3
level_0_4 = 105 Ice Town.rlv,4
level_0_5 = 106 Heaven Can Wait II.rlv,5
level_0_6 = 107 How Do We Get Down There.rlv,6
level_0_7 = 108 Jacklemmings.rlv,7

# Rating 1 - Lemmings Companion (The Prima Publishing Levels)

level_1_0 = 201 Digger Conversions.rlv,0
level_1_1 = 202 For Every Lemming Turn Turn.rlv,1
level_1_2 = 203 Alternate Route.rlv,2
level_1_3 = 204 Bridge Delay.rlv,3
level_1_4 = 205 The Prima Publishing Level.rlv,4
level_1_5 = 206 Lemming Excavation.rlv,5
level_1_6 = 207 Let's Go Sledding.rlv,6
level_1_7 = 208 The Pipeline.rlv,7
level_1_8 = 209 Wild World of Lemmings.rlv,8
level_1_9 = 210 Winter Lemmingland.rlv,9
level_1_10 = 211 Oh No Squish.rlv,10
level_1_11 = 212 Watch Your Step.rlv,11
level_1_12 = 213 Dolly Dimple.rlv,12
level_1_13 = 214 Which Way Do We Go.rlv,13
level_1_14 = 215 Old MacDonald Had A Farm.rlv,14
level_1_15 = 216 Congratulations.rlv,15

# Rating 2 - DMA Bonus Levels

level_2_0 = 301 The Apple Computer Level.rlv,0
level_2_1 = 302 Lemming Lament.rlv,1
level_2_2 = 303 Something weighing on your mind.rlv,2
level_2_3 = 304 Battle at Midway.rlv,3
level_2_4 = 305 One Way to Freedom.rlv,4
level_2_5 = 306 Vacation in Gemland.rlv,5
level_2_6 = 307 Through the graveyard.rlv,6
level_2_7 = 308 Don't Make The Wrong Choice!.rlv,7
level_2_8 = 309 Go for it!.rlv,8
level_2_9 = 310 Going their separate ways.rlv,9
level_2_10 = 311 It's not over 'til it's over.rlv,10
level_2_11 = 312 Ohayo Lemming-san.rlv,11
level_2_12 = 313 Must Go Camping.rlv,12
level_2_13 = 314 Try Try Again.rlv,13
level_2_14 = 315 Tribute to Tribute to MC Escher.rlv,14
level_2_15 = 316 Return of the Running Jump.rlv,4